### ISSUE TITLE
How to build this for Fedora with proprietary FFMPEG codecs installed?

### ISSUE THREAD

**Issue by kylxbn** [sdroege/ebur128#54]
I use Fedora with the proprietary codecs and the complete FFMPEG software (including x264) installed. However, I cannot build the source because:

```
Problem 1: package libavformat-free-devel-6.0-2.fc38.i686 from fedora requires libavformat-free(x86-32) = 6.0-2.fc38, but none of the providers can be installed
Problem 2: package libavcodec-free-devel-6.0-2.fc38.i686 from fedora requires libavcodec-free(x86-32) = 6.0-2.fc38, but none of the providers can be installed
Problem 3: package libswresample-free-devel-6.0-2.fc38.i686 from fedora requires libswresample-free(x86-32) = 6.0-2.fc38, but none of the providers can be installed
```

Trying to install the RPM file directly results in a similar thing.

Can you please help me install the dependencies needed to build this?

**Comment by sdroege** [comment]
How is this related to the code in this repository? What are you trying to do exactly?

**Comment by kylxbn** [comment]
I'm sorry. This was a mistake and is posted on the wrong repository. Please ignore. I apologize.

**Comment by sdroege** [comment]
Ok, no worries :)
