### ISSUE TITLE
Provide possibility for Album Gain calculations

### ISSUE THREAD

**Issue by Holzhaus** [sdroege/ebur128#58]
I have multiple track that I would like to analyze individually and then compute the album gain (which is the gain of the concatenation of all tracks). I'd like to avoid analyzing all the audio data twice. If I understand correctly this could be archieved like this:

```python
album_gating_block_count = 0
album_track_energy_sum = 0

for track in album_tracks:
    album_gating_block_count += track.gating_block_count
    album_track_energy_sum += track.energy * track.gating_block_count

album_energy = album_track_energy_sum / album_gating_block_count
```

This means I need the energy for each track and the number of gating blocks, so that I can compute the overall energy of the album. I can calculate each track energy from its loudness value by inverting https://github.com/sdroege/ebur128/blob/main/src/utils.rs#L25, but I do not know how many gating blocks the track has.

Could you expose methods for this?

**Comment by sdroege** [comment]
Sounds like a good idea. Do you want to provide a PR for exposing methods that allow you to calculate the album gain? If you can also add an example that makes use of them to calculate album gain that would be even better :)

**Comment by Holzhaus** [comment]
Alright, I opened PR #59.

**Comment by Holzhaus** [comment]
@sdroege Do you want to tag a new release? Or anything else missing?

**Comment by sdroege** [comment]
Nothing missing, I was going to do that today :) See https://github.com/sdroege/ebur128/pull/60
